### ISSUE TITLE
Spatial lookup

### ISSUE THREAD

**Issue by DocKDE** [nonnominandus/pdbtbx#65]
Hi,
I saw that you updated the docs with the version upgrade. If I'm reading the `rtree` docs correctly (and from my own experience), the `locate_within_distance` takes a squared distance as input so in your example the atoms within 12.5^0.5 would be located.
You may want to check up on that and adjust tests accordingly.

**Comment by nonnominandus** [comment]
Thanks a lot for the issue, it is fixed now. I seem to have overlooked this fact.

**Comment by DocKDE** [comment]
It's not terribly intuitive, I mostly stumbled over this because it's an integral part of my code :)
