### ISSUE TITLE
PDB file recognition

### ISSUE THREAD

**Issue by DocKDE** [nonnominandus/pdbtbx#67]
I recently tried to point the `openPDB` function at a random text file and it seems no error is thrown when that happens. I realize this is not an intended use of the function at all but I thought it might be worth a thought to add a warning or breaking error for such cases. Something like "No data could be parsed from file, please make sure it is a valid PDB file" maybe.
Would that maybe be reasonable?

**Comment by nonnominandus** [comment]
I totally agree that such an error is useful. I propose to make them be triggered by the amount of atoms parsed, so if there are no atoms found when the parsing is finished it should generate an error. I would assume that a breaking error is more appropriate, but if you think otherwise please let me know.

**Comment by DocKDE** [comment]
Yes, this is pretty much exactly what I was thinking.

**Comment by nonnominandus** [comment]
Great, then I will build it in in the future, but if you want you could also take a shot.

**Comment by DocKDE** [comment]
I haven't really looked at the parsing function yet, the last time I tried it scared me :D 
If I get around to it I'll take a look but no promises...

**Comment by DocKDE** [comment]
So I just took a look at the parsers. It seems to me a good place for this validation would be the `validate` function since it's called during the parsing of PDB and mmCIF files and has `&PDB` as argument so checking for presence of any atoms would be trivial. However, the functions seems to only be used for validation of models if more than one is present. Do you think writing a separate function would be more appropriate or would expanding this one be suitable?

**Comment by DocKDE** [comment]
I submitted a tentative pull request with the most straightworward way I could think of. I couldn't add any sensible context to the error since the `validate` function doesn't have access to the file name but I think that's not much of an issue.
